services:
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-service
    ports:
      - "8761:8761"
    networks:
      - spring-network
    restart: always

  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    restart: always
    networks:
      - spring-network

  task-service:
    image: task-service:latest
    build:
      context: ./task-service
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    restart: always
    networks:
      - spring-network

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    restart: always
    networks:
      - spring-network
      
  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    restart: always
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

